### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by DominiqueMakowski** [LRydin/MFDFA#30]
Hi @LRydin! Just a quick check, 

If I'm not mistaken, here you compute *Tau(q)* as :

https://github.com/LRydin/MFDFA/blob/a6e9bfdc88157baafc04e72aea6ff6a833a0cfa9/MFDFA/singspect.py#L163

However, in **Orozco-Duque, A., Novak, D., Kremen, V., & Bustamante, J. (2015). Multifractal analysis for grading complex fractionated electrograms in atrial fibrillation. Physiological Measurement, 36(11), 2269–2284. doi:10.1088/0967-3334/36/11/2269** they compute it as:

![image](https://user-images.githubusercontent.com/8875533/166179423-c55a6c95-75b9-4d86-ad76-075f718a6972.png)

which would be `(q-1) * slopes`?

Is it equivalent or is there something I missed?

**Comment by DominiqueMakowski** [comment]
Also, in the same paper, they suggest a global measure hFI:

![image](https://user-images.githubusercontent.com/8875533/166181390-ff6f98b7-9722-41a6-b6ba-ed3ab74c378b.png)

What do you think of it?
I'd like to add that to NK, but I'm not sure how does it translate to python 🙈

**Comment by DominiqueMakowski** [comment]
I gave it a [try](https://github.com/neuropsychology/NeuroKit/blob/a33dc6145e06e4948311f92d5ab7fe1cfd55ca49/neurokit2/complexity/fractal_dfa.py#L332-L373), but let me know if you find the time to give it a look! I really think it needs a double check :)

**Comment by LRydin** [comment]
Hey @DominiqueMakowski! Sorry, I totally missed the notification!

So, to your first question: The formulation in Orozco-Duque _et al._ is based on the scaling of the partition function _Z_, which is slightly different that our formulation in DFA and MFDFA. There is nothing incorrect in that paper, Orozco-Duque _et al._ are simply introducing an identical formulation based on the notion of the Hausdorff dimension (it's that very interesting question of, e.g., taking a map of the UK and measuring the shoreline, measuring the total lenght of the shoreline, progressively with smaller and smaller sticks).

If you continue down you find Eq. (14):
![eq14](https://user-images.githubusercontent.com/47757762/168025209-0b2451c4-6605-4200-ad4c-a9e7e01bd784.png)
wherein you find the relation of the fluctuation function from MFDFA with _h(q)_. Which then leads us to a construction wherein _τ(q) = q*h(q) - 1_. So our formulation is correct :).

Now to the question on the hFI:
From the edit that you included, you can actually get this fairly easily from the singularity spectrum _f(α)_ in [L. 166-228](https://github.com/LRydin/MFDFA/blob/a6e9bfdc88157baafc04e72aea6ff6a833a0cfa9/MFDFA/singspect.py#L166). Then you have _h(q)_ and you can apply a derivative twice :). Personally I don't like this measure too much for a simple reason. If you check their Fig. 3:
![fig3](https://user-images.githubusercontent.com/47757762/168028302-60a0dfdc-ae7b-4f62-8368-cd0ed5faf24b.png)
you can see _Δ²h(q)_, from which hFI is simply the difference between the minimum and maximum. Now you only see a real change in the left plots as you get close to _q=0_, which is also where both MFDFA and WTMM don't work (or work very poorly). Whether this measure has any physical meaning, I cannot judge, but it could be fraught with numerical uncertainties. But from the paper it actually seems they get something meaningful out of it, so that's good :). Anyway, your implementation seems correct to me :).

Suggestion:
Maybe it is better to use *np.gradient()* in [L.361](https://github.com/neuropsychology/NeuroKit/blob/a33dc6145e06e4948311f92d5ab7fe1cfd55ca49/neurokit2/complexity/fractal_dfa.py#L361), which should be smoother:
```python
np.sum(np.gradient(np.gradient(out["h"])) ** 2) / (2 * np.max(np.abs(q)) + 2)
```
But overall it all seems correct to me :).

Hope it helps!

P.S.: Indeed this new paper from 2021 says _hFI = Δ²α_, and that does not seem correct to me :/. Odd.

**Comment by DominiqueMakowski** [comment]
Thanks a lot @LRydin for the clarification! 

PS: I'm almost done with a big overhaul of all the complexity functions in NK for its next 2.0 release, with a [new website documentation](https://neuropsychology.github.io/NeuroKit/functions/functions_complexity.html) and all, feel free to hop by anytime if you have any suggestions for improvements or features :)

Also, if you have any idea how to translate the modified formula to compute the slope when *q* = 0 (in Faini 2021) let me know 😁 

![image](https://user-images.githubusercontent.com/8875533/168049397-36235e61-0dee-4ac5-86a5-58a54feb1167.png)
