### ISSUE TITLE
Colored Noise Singularity Spectrum Issues

### ISSUE THREAD

**Issue by rsautter** [LRydin/MFDFA#34]
There is negative alpha values when testing colored noise series of size 2**15,  in a set of q  = np.array([5,6,7,8,9]) , with MFDFA==0.4.2.

**Comment by LRydin** [comment]
That somewhat does not sound too surprising, there is a small issue with testing noise directly due to the regularity of the process. Could you try and introduce instead `X` (the time series) into `MFDFA` but intead `np.cumsum(X)`?

---

The point is that when you consider a non-integrated process, e.g., just noise, the process has a regularity which is `-1` of an integrated process (the difference between a noise and a motion). This leads to `α → α - 1`. Are the negative values of `α` larger than `-1`?

**Comment by LRydin** [comment]
NB: Need to add a flag to [`singularity_spectrum`](https://github.com/LRydin/MFDFA/blob/3ba6b7c00968adc5f67bfc53d5d472894332aaed/MFDFA/singspect.py#L22) and all related measures to ensure noise is treated with according regularity.

**Comment by LRydin** [comment]
@rsautter I've corrected this issue in the new version `v0.4.3`. You can use `pip` to bump to this newer version:

```
pip install --upgrade MFDFA
```
Hopefully this solves your issue.

**Comment by rsautter** [comment]
It's working! Thanks
