### ISSUE TITLE
Examples on electricity prices

### ISSUE THREAD

**Issue by XiaoPachong999** [LRydin/MFDFA#36]
Hello Dear Professor, I am very interested in the MFDFA package you have written. I would like to reproduce the example of electricity price in your MFDFA package, but I do not see the dataset and code for electricity price fluctuation in your public code package. I would like to ask you if you could add this one example so that I can learn it. I look forward to hearing from you!

**Comment by LRydin** [comment]
Hey there @XiaoPachong999! Yeah, that is the one dataset that we cannot make public because it is proprietary :(. I always like to share the data used, but this one is behind a paywall.

I can nevertheless point you to the ENTSO-E Transparency platform, to the section of [Day-Ahead Prices](https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show) (select 
BZN|DE-LU). There you can find and download Day-Ahead prices from Germany (and many other countries) and try to analyse that data.

Hope this helps!
Cheers,
Leo

**Comment by XiaoPachong999** [comment]
Dear Professor, Thank you for your reply! I had some problems with the code when trying to reproduce the example on electricity price fluctuations using other datasets, that is, I had problems with moving the window. The error is: TypeError: MFDFA() got an unexpected keyword argument 'extension'. I would like a copy of your code on tariff fluctuations to study. Could you please send me a copy? I look forward to hearing from you again!

**Comment by LRydin** [comment]
Hey @XiaoPachong999, try `extensions` instead of `extension`, like this

```python
lag, fluct = MFDFA(data, lag, q, extensions={'window': 1})
```
I think we might have changed that parameter to the plural form at some point.

**Comment by XiaoPachong999** [comment]
Thank you again for your reply！

**Comment by LRydin** [comment]
Sounds good, I'm gonna close this issue, but feel free to write if you need anything!
